branch-defaults:
  feature/deployTest:
    environment: WebGenieReactApp-dev
    group_suffix: null
global:
  application_name: WebGenieReactApp
  branch: null
  default_ec2_keyname: null
  default_platform: Node.js 16 running on 64bit Amazon Linux 2
  default_region: ap-northeast-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
