const DISPATCH_TYPE = {
  INSERT_LOCAL_IMAGE: "SET_LOCAL_IMAGE_SRC",
  INSERT_IMAGE_URL: "SET_IMAGE_URL",
  VALID_IMAGE_URL: "SET_IMAGE_URL_AVAILABILITY",
  INITIAL_SETTING_EDITOR: "SET_EDITOR",
  HANDLE_LOG_IN_TOKEN_INFORMATION: "HANDLE_LOG_IN_TOKEN_INFORMATION",
  GET_OR_POST_EDITOR_CODE: "SET_EDITOR_DATA",
  HANDLE_LOG_IN_USER_INFORMATION: "HANDLE_LOG_IN_USER_INFORMATION",
  CHANGE_BACKGROUND_COLOR: "SET_BACKGROUND_COLOR",
  CHANGE_BUTTON_AND_FONT_COLOR: "SET_COLOR",
  CHANGE_LOCATION_ELEMENT: "SET_CURRENT_ELEMENT",
  CHANGE_EDITOR_TITLE: "SET_EDITOR_TITLE",
  CHANGE_IMAGE_STYLE: "SET_IMAGE_STYLE",
  RESET_IMAGE_STYLE: "RESET_IMAGE_STYLE",
  CHANGE_FONT_STYLE: "SET_FONT_STYLE",
  RESET_FONT_STYLE: "RESET_FONT_STYLE",
};

export default DISPATCH_TYPE;
